version: "3.8"

services:

  # ---------------- API GATEWAY ----------------
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      USER_SERVICE_URL: http://user-service:8001
      RENTAL_SERVICE_URL: http://rental-service:8002
      ANALYTICS_SERVICE_URL: http://analytics-service:8003
      AGENTIC_SERVICE_URL: http://agentic-service:8004
    depends_on:
      - user-service
      - rental-service
      - analytics-service
      - agentic-service
    networks:
      - rentpi-net

  # ---------------- USER SERVICE ----------------
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      JWT_SECRET: secret123
    networks:
      - rentpi-net

  # ---------------- RENTAL SERVICE ----------------
  rental-service:
    build: ./rental-service
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
    networks:
      - rentpi-net

  # ---------------- ANALYTICS SERVICE ----------------
  analytics-service:
    build: ./analytics-service
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
    networks:
      - rentpi-net

  # ---------------- AGENTIC SERVICE ----------------
  agentic-service:
    build: ./agentic-service
    ports:
      - "8004:8004"
    environment:
      PORT: 8004
    networks:
      - rentpi-net

networks:
  rentpi-net:
    driver: bridge